pulp/pulp-certguard

.travis.yml
COMMITMENT
LICENSE
setup.py

Additional Setup.

---

README.rst
docs/installation.rst

Fix app label change on README

Docs update

---

.travis/install.sh
.travis/script.sh
README.rst

- add file_plugin to travis
- replace pulp-manager by django-admin
- fix endpoint on README
[noissue]

Add file_plugin to travis, replace pulp-manager with django-admin

---

.travis.yml

The existing creds are failing to upload so I regenerated them.
https://pulp.plan.io/issues/4601
closes #4601

Regenerate PyPI creds

---

.travis/script.sh
README.rst

Change Pulp 3 Default Ports
https://pulp.plan.io/issues/4556
docs updates too:
https://pulp.plan.io/issues/4594
Content: 8080 -> 24816
API: 8000 -> 24817
[noissue]
Required PR: https://github.com/pulp/pulpcore/pull/75

Default ports

---

pulp_certguard/tests/functional/api/test_certguard.py
pulp_certguard/tests/functional/utils.py

ref #4720
https://pulp.plan.io/issues/4720

Update tests based on publication path change

---

pulp_certguard/tests/functional/api/test_certguard.py
pulp_certguard/tests/functional/constants.py

Required PR: https://github.com/pulp/pulpcore/pull/117
Required PR: https://github.com/pulp/pulpcore-plugin/pull/95
Required PR: https://github.com/pulp/pulp_file/pull/217
Required PR: https://github.com/PulpQE/pulp-smash/pull/1205
ref #4785
https://pulp.plan.io/issues/4785

Adapt to Master/Detail Distribution change

---

pulp_certguard/tests/functional/api/test_certguard.py
pulp_certguard/tests/functional/constants.py
pulp_certguard/tests/functional/utils.py

ref #4720
https://pulp.plan.io/issues/4720

Remove file publisher stuff from tests

---

contrib/yum/Makefile
contrib/yum/README
contrib/yum/certguard.conf
contrib/yum/certguard.py
docs/index.rst
docs/yum-howto.rst

This PR shows how I used a certguard protected repo to distribute
updates to rhel boxes using yum.
Feedback encouraged and appreciated.

Yum mini-howto

---

pulp_certguard/app/models.py

Declaring default_related_name
related to: https://github.com/pulp/pulpcore/pull/259
ref #4681

dealing with pulpcore default_related_name

---

CHANGES.rst
CHANGES/4875.doc
pulp_certguard/__init__.py
setup.py

Version 0.1.0rc2 Release

---

pulp_certguard/__init__.py
setup.py

Version bump to 0.1.0rc3.dev

---

setup.py

Remove outdated dependency on pulpcore-plugin

---

CHANGES.rst
CHANGES/5457.removal
CHANGES/5625.feature
CHANGES/5625.removal
pulp_certguard/__init__.py
setup.py

Create version 0.1.0rc3

---

.travis.yml
.travis/before_install.sh
.travis/before_script.sh
.travis/cherrypick.py
.travis/cherrypick.sh
.travis/install.sh
.travis/publish_client_gem.sh
.travis/publish_client_pypi.sh
.travis/publish_plugin_pypi.sh
.travis/script.sh
.travis/validate_commit_message.py
functest_requirements.txt
template_config.yml

Updating travis

---

setup.py

Fixing pulpcore requirement to get builds passing

---

pulp_certguard/app/models.py
pulp_certguard/app/utils.py
pulp_certguard/tests/functional/utils.py

Add exception output to rhsm import failure

---

CHANGES/6546.doc
docs/installation.rst
docs/usage.rst

https://pulp.plan.io/issues/6546
closes #6546

Add docs on manual install of `rhsm`

---

README.rst

Updating Travis badge to travis-ci.com

---

setup.py

Removes pulpcore max version

---

.travis/release.py

Fix path on release script

---

.bumpversion.cfg
.travis/release.py
CHANGES.rst
pulp_certguard/__init__.py
requirements.txt
setup.py

Redmine query of issues to close:
https://pulp.plan.io/issues?set_filter=1&status_id=*&issue_id=
Release commit == a124a8e

Release 1.0.0

---

.bumpversion.cfg
CHANGES.rst
CHANGES/7177.bugfix
pulp_certguard/__init__.py
requirements.txt
setup.py

Redmine query of issues to close:
https://pulp.plan.io/issues?set_filter=1&status_id=*&issue_id=7177
Release commit == 3d05706

Release 1.0.1

---

.ci/ansible/Containerfile.j2
.ci/ansible/start_container.yaml
.ci/scripts/docs-builder.py
.ci/scripts/release.py
.ci/scripts/schema.py
.github/workflows/scripts/before_install.sh
.github/workflows/scripts/script.sh
template_config.yml

This accommodates for a change in pulpcore that will effect the CI.
https://github.com/pulp/pulpcore/pull/1102
[noissue]

Update plugin template

---

setup.py

Changed setup.py to use " instead of ' around strings.

---

.github/workflows/scripts/before_install.sh
.github/workflows/scripts/install.sh
requirements.txt
template_config.yml

Update required version of pulpcore to >-3.10,<3.15

---

.github/workflows/scripts/post_before_script.sh

Removes the post_before_script.sh

---

.github/workflows/release.yml
template_config.yml

Also re-ran plugin-template with the latest changes
[noissue]

Updates template_config.yml with update_redmine: true

---

.ci/ansible/Containerfile.j2
.github/workflows/scripts/script.sh
CHANGES/9054.removal
CONTRIBUTING.rst
setup.py

Drop support for Python < 3.8

---

doc_requirements.txt

Clean up doc_requirements.

---

functest_requirements.txt
pulp_certguard/tests/functional/__init__.py
setup.py

Add pytest plugin parts and some fixtures

---

pulp_certguard/tests/functional/__init__.py

Remove cid fixture provided by pulpcore

---

template_config.yml

Remove an unused template var

---

pyproject.toml

Switch towncrier links to github issues

---

doc_requirements.txt

Pin the mistune version.

---

CHANGES/145.bugfix
pulp_certguard/app/models.py

Taught bad-certificate-failures emit warnings to the server-log.

---

pulp_certguard/app/__init__.py

Add domains compatibility

---

CHANGES/232.bugfix
pulp_certguard/app/serializers.py

Catch openssl errors while parsing certificates

---

template_config.yml

Add 1.6 to ci-supported versions.

---

pulp_certguard/tests/functional/__init__.py

Fix api client fixture for session scope

---

requirements.txt

Raise core-lb to 3.14.9.

---

CHANGES/252.bugfix
requirements.txt

Push max-compat to core/3.40.

---

pulp_certguard/tests/functional/api/test_rhsm_certguard.py
pulp_certguard/tests/functional/api/test_x509_certguard.py

Deactivate test-cases if domains=true.

---

ci_requirements.txt

Restrict pulp_file version in ci tests

---

functest_requirements.txt
unittest_requirements.txt

Pin pytest<8.

---

requirements.txt

Bump PyOpenSSL<0.25
